# appveyor.yml - https://www.appveyor.com/docs/lang/python
---
image:
  - Visual Studio 2019

environment:
  matrix:
  - TOXENV: py39

build: false

install:
  - py -m pip install flask

build_script:
  - py ./some_app.py