# appveyor.yml - https://www.appveyor.com/docs/lang/python
---
image:
  - Visual Studio 2019

PACKAGE: "poetry"

install:
  - pip install poetry
  - poetry install
#  - py -m pip install flask
  - poetry --version
  - flask --version

#build_script:
#  - py ./some_app.py