# appveyor.yml - https://www.appveyor.com/docs/lang/python
---
image:
  - Visual Studio 2019

install:
  - pip install poetry
  - poetry install
#  - py -m pip install flask

build_script:
  - py ./some_app.py