environment:

  matrix:

    # For Python versions available on Appveyor, see
    # https://www.appveyor.com/docs/windows-images-software/#python
    # The list here is complete (excluding Python 2.6, which
    # isn't covered by this document) at the time of writing.

    - TOXENV: py39

install:
  # We need wheel installed to build wheels
  - py -m pip install flask

build: false

build_script:
  - py ./some_app.py